name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  sn_progress_dialog: ^1.1.3
  fluttertoast: ^8.2.4
  flutter_masked_text2: ^0.9.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_image_slideshow: ^0.1.6
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_credit_card: ^4.0.1
  flutter_custom_clippers: ^2.1.0
  # fluttertoast: ^8.2.4
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.4.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  google_sign_in: ^6.1.6
  smooth_page_indicator: ^1.1.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0
  day_night_switcher: ^0.2.0+1
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/img/
  fonts:
    - family: ptsbold
      fonts:
        - asset: assets/fuentes/PTSerif-bold.ttf
  uses-material-design: true
