name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  sn_progress_dialog: ^1.1.3
  fluttertoast: ^8.2.4
  flutter_masked_text2: ^0.9.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_image_slideshow: ^0.1.6
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  # geocoder: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/img/
  uses-material-design: true
